repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: nginx-ingress
    version: 1.41.2

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: 0.9.0

  - name: chartmuseum
    chart: stable/chartmuseum
    namespace: chartmuseum
    version: 2.13.1
    values:
      - "../chartmuseum/values.yaml"

  - name: harbor
    chart: harbor/harbor
    namespace: harbor
    version: 1.1.2
    values:
      - "../harbor/values.yaml"





environments:
  default:
    values:
    - domain: 35.228.138.157.nip.io
    - issuer: letsencrypt-staging
  production:
    values:
    - domain: 35.228.138.157.nip.io
    - issuer: letsencrypt-production

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io

helmDefaults:
  wait: true

templates:
  template: &template
    missingFileHandler: Warn
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.11.1
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 0.9.0
  hooks:
  - events:
    #- prepare
    - presync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - apply
    - -f
    - https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
  - events:
    #- prepare
    - presync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - label
    - namespace
    - "{{`{{ .Release.Namespace }}`}}"
    - certmanager.k8s.io/disable-validation="true"
  - events:
    #- cleanup
    - postsync
    showlogs: true
    #command: echo
    command: kubectl
    args:
    - apply
    - -f
    - kubernetes-templating/cert-manager/clusterissuer-{{ .Values.issuer }}.yaml
- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.1.2
  values:
  <<: *template




  ---

values:
  - namespaces:
      - nginx-ingress
      - cert-manager
      - harbor

repositories:
  # helmfile uses stable https://kubernetes-charts.storage.googleapis.com
  # by default
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

templates:
  default: &default
    wait: true
    timeout: 240
    # atomic: true
    namespace: "{{`{{ .Release.Name }}`}}"
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml
  raw: &raw
    chart: incubator/raw
    wait: true
    timeout: 120
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
  # Currently helm3 can't create namespaces
  # https://github.com/roboll/helmfile/issues/891
  - name: namespaces
    chart: incubator/raw
    namespace: default
    values:
      - resources:
{{ range $key := $.Values.namespaces }}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: {{ . }}
            spec:
{{ end }}


  - name: nginx-ingress
    <<: *default
    chart: stable/nginx-ingress
    version: 1.11.1
    needs:
      - default/namespaces


  - name: cert-manager
    <<: *default
    chart: jetstack/cert-manager
    version: 0.9.0
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["label", "--overwrite", "namespace", "cert-manager", "certmanager.k8s.io/disable-validation=true"]
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-f", "https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml"]
    needs:
      - default/namespaces
      - nginx-ingress/nginx-ingress


  - name: cluster-issuer
    <<: *raw
    namespace: default
    needs:
      - default/namespaces
      - cert-manager/cert-manager
      - nginx-ingress/nginx-ingress


  - name: harbor
    <<: *default
    chart: harbor/harbor
    version: 1.1.2
    needs:
      - default/namespaces
      - cert-manager/cert-manager
      - nginx-ingress/nginx-ingress
      - default/cluster-issuer