apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  namespace: web
  labels:
    app: web
    prometheus: default
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: web
      prometheus: default
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    path: '/metrics'
